// this file is accessible for entire framework
const { defineConfig } = require("cypress");
// for cucumber integration
const preprocessor = require("@badeball/cypress-cucumber-preprocessor");
const browserify = require("@badeball/cypress-cucumber-preprocessor/browserify");

async function setupNodeEvents(on, config) {
  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await preprocessor.addCucumberPreprocessorPlugin(on, config);

  on("file:preprocessor", browserify.default(config));

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}



module.exports = defineConfig({
  projectId: "2u8f6b",
  //This is a unique ID generated by Cypress Cloud when you create a new project.
  // Adding this line to your configuration file will sync the local project with the project in Cypress Cloud.
  // This ensures appropriate reporting

  defaultCommandTimeout: 6000,
  env:{
    url: "https://rahulshettyacademy.com/angularpractice/"
  },
  retries:{
    runMode: 1
    // this is how to set up rerun in cypress. to Find it go to project settings
  },
  e2e: {
    setupNodeEvents,
    // implement node event listeners here,

    // specifying test files location
    specPattern: '**/*.feature'
    //  'cypress/integration/examples/*.js'

    // screenshotsFolder: 'cypress/screenshots'
  },
});
